#!/bin/sh -eux
: ${K8S_SU_USER:=coopadmin}

TMP=$(mktemp -d)
cd $TMP

# Keyer
touch $TMP/keys
if [ ! -z "$KUBASH_SET_ROOT_PW" ]; then
	echo "$KUBASH_SET_ROOT_PW" |passwd foo --stdin
else
  echo 'no root passwd given, not setting'
fi
if [ ! -z "$KUBASH_SET_SU_PW" ]; then
	echo "$K8S_SU_USER:$KUBASH_SET_SU_PW" | chpasswd
else
  echo 'no su passwd given, not setting'
fi
if [ ! -z "$KEYS_URL" ]; then
  curl --silent -L "$KEYS_URL"  >> $TMP/keys 
else
  echo 'no KEYS_URL given'
fi
if [ ! -z  "$KEYS_TO_ADD" ]; then
  echo "$KEYS_TO_ADD" >>  $TMP/keys
else
  echo 'no KEYS_TO_ADD given'
fi
mkdir -p /root/.ssh
chmod 700 /root/.ssh
cp $TMP/keys /root/.ssh/authorized_keys
chmod 600 $TMP/keys /root/.ssh/authorized_keys

ls -lh /root/.ssh
#cat /root/.ssh/authorized_keys

useradd -s /bin/bash $K8S_SU_USER
groupadd -rf docker
gpasswd -a $K8S_SU_USER docker
groupadd -rf sudo
gpasswd -a $K8S_SU_USER sudo
chmod 777 $TMP
mkdir -p /home/$K8S_SU_USER/.ssh
cp $TMP/keys /home/$K8S_SU_USER/.ssh/authorized_keys
chmod 600 /home/$K8S_SU_USER/.ssh/authorized_keys
chmod 700 /home/$K8S_SU_USER/.ssh
echo 'PATH=/usr/local/bin:$PATH' >> /home/$K8S_SU_USER/.bash_profile
chown -R $K8S_SU_USER. /home/$K8S_SU_USER

rm -Rf $TMP
