#!/bin/sh -eux
: ${K8S_SU_USER:=coopadmin}

TMP=$(mktemp -d)
trap "rm -Rf $TMP" EXIT
cd $TMP

useradd -s /bin/zsh $K8S_SU_USER
groupadd -rf docker
gpasswd -a $K8S_SU_USER docker
groupadd -rf sudo
gpasswd -a $K8S_SU_USER sudo

# Keyer
touch $TMP/keys
if [ ! -z "$KUBASH_SET_ROOT_PW" ]; then
  echo 'root passwd given, setting'
	echo "root:$KUBASH_SET_ROOT_PW" | chpasswd
else
  echo 'no root passwd given, not setting'
fi
sleep 3
if [ ! -z "$KUBASH_SET_SU_PW" ]; then
  echo 'su passwd given, setting'
	echo "$K8S_SU_USER:$KUBASH_SET_SU_PW" | chpasswd
else
  echo 'no su passwd given, not setting'
fi
if [ ! -z  "$KEYS_TO_ADD" ]; then
  echo 'KEYS_TO_ADD given'
  echo "$KEYS_TO_ADD" >> $TMP/keys
else
  echo 'no KEYS_TO_ADD given'
fi
if [ ! -z "$KEYS_URL" ]; then
  echo 'KEYS_URL given'
  curl --silent -L "$KEYS_URL" >> $TMP/keys
else
  echo 'no KEYS_URL given'
fi

mkdir -p /root/.ssh
chmod 700 /root/.ssh
ssh-keygen  -N "" -t ed25519 -f /root/.ssh/id_ed25519
cp $TMP/keys /root/.ssh/authorized_keys
cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
chown -R root. /root/.ssh

ls -lh /root/.ssh
#cat /root/.ssh/authorized_keys

chmod 777 $TMP
mkdir -p /home/$K8S_SU_USER/.ssh
cp -a /root/.ssh /home/$K8S_SU_USER/
chmod 600 /home/$K8S_SU_USER/.ssh/authorized_keys
chmod 700 /home/$K8S_SU_USER/.ssh
echo 'PATH=/usr/local/bin:$PATH' >> /home/$K8S_SU_USER/.bash_profile
chown -R $K8S_SU_USER: /home/$K8S_SU_USER/.ssh

# get oh my zsh install script
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o  $TMP/ohmyzsh.sh
# install oh-my-zsh
sh $TMP/ohmyzsh.sh "" --unattended
sudo cp -a /home/vagrant/.oh-my-zsh /home/$K8S_SU_USER/
sudo cp -a /home/vagrant/.oh-my-zsh /root/
sudo cp -a /home/vagrant/.zshrc /home/$K8S_SU_USER/
sudo cp -a /home/vagrant/.zshrc /root/
sudo chown --quiet -R $K8S_SU_USER: /home/$K8S_SU_USER
sudo chown --quiet -R root: /root
rm $TMP/ohmyzsh.sh

# change shell to zsh
sudo chsh -s $(which zsh) root
sudo chsh -s $(which zsh) $K8S_SU_USER
