stages:
  - build
  - test 
  - deploy 

build_job:
  stage: build
  script:
    - echo 'build'

fulltest-build:
  stage: build
  tags:
    - fulltest
  only:
    - fulltest
  script:
    - echo 'fulltest1build'
    - ls
    - pwd

rspec:
  stage: test
  script:
    - echo 'rspec'

rubocop:
  stage: test
  script:
    - echo 'rubocop'

fulltest-test:
  stage: test
  tags:
    - fulltest
  only:
    - fulltest
  script:
    - echo 'fulltest1'
    - ls

fulltest-deploy:
  stage: deploy
  tags:
    - fulltest
  only:
    - fulltest
  script:
    - echo 'fulltest1deploy'
    - ls
    - pwd

deploy_job:
  stage: deploy
  script:
    - echo 'deploy'
