version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.5

templates:
  machine_job_template: &machine_job_template
    machine: true
    working_directory: /home/circleci/kubash
    environment:
      DEBIAN_FRONTEND: "noninteractive"

jobs:
  pupernetes:
    <<: *machine_job_template
    steps:
      - checkout
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.10.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config --dns-check
      - run:
          name: kubectl
          command: kubectl get all
      - run:
          name: something
          command: echo "let's go ..."
  check:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOFLAG: -mod=readonly

    resource_class: small

    steps:
      - checkout
      - run:
          name: Check dependency licenses
          command: bash bootstrap

  acceptance-test:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

    environment:
      GO_VERSION: "1.12.3"
      K8S_VERSION: v1.15.3
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v1.3.1
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
      GOPATH: /go
      DOCKER_LATEST: 1
      GIN_MODE: release

    steps:
      - run:
          name: Setup minikube
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

      - run:
          name: Start minikube
          background: true
          command: |
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 4096 --kubernetes-version=${K8S_VERSION}

      - run:
          name: Setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config

      - checkout

      - run:
          name: Create go directory
          command: |
            sudo mkdir /go
            sudo chmod 777 /go

      - run:
          name: Setup golang
          command: |
            sudo rm -rf /usr/local/go
            curl -Lo go.linux-amd64.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz && rm go.linux-amd64.tar.gz

      - run:
          name: Wait for minikube
          command: |
            timeout 180s bash \<<EOT
              set -o pipefail
              function is_ready()
              {
                kubectl get nodes -o json \
                  | jq '.items[].status.conditions[] | select(.type=="Ready" and .status=="True")'
              }

              until is_ready
              do
                sleep 1
              done
            EOT

      - run:
          name: Setup helm
          command: |
            curl -L https://git.io/get_helm.sh | bash
            helm init
            helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com/

workflows:
  version: 2
  ci:
    jobs:
      - pupernetes
      - check
      - acceptance-test:
          requires:
            - check
