# Orb 'banzaicloud/helm@0.0.5' resolved to 'banzaicloud/helm@0.0.5'
version: 2
jobs:
  check:
    docker:
    - image: circleci/golang:1.14
      environment:
        GOFLAG: -mod=readonly
    - image: vault:1.1.0
      environment:
        SKIP_SETCAP: true
        KUBERNETES_VERSION: v1.18.6
        VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
        TERM: dumb
        GOPATH: /home/circleci/.go

    resource_class: small
    working_directory: /home/circleci/.kubash
    steps:
    - checkout
    - run:
        name: Check dependency licenses
        command: bash bootstrap
  acceptance-test:
    machine: true
    working_directory: /home/circleci/.kubash
    environment:
    - DEBIAN_FRONTEND: noninteractive
    - TERM: dumb
    steps:
    - checkout
    - run:
        name: download
        command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.11.0/pupernetes
          -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
    - run:
        name: apt
        command: sudo apt-get update -qq && sudo apt-get install -yqq systemd
    - run:
        name: run
        command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd
          --kubectl-link /usr/local/bin/kubectl --kubeconfig-path $HOME/.kube/config
          --dns-check
    - run:
        name: kubectl
        command: kubectl get all
    - run:
        name: Setup helm
        command: |
          curl -L https://git.io/get_helm.sh | bash
          helm init
          helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com/
    - run:
        name: Upgrade Pip
        command: |
          pip install --upgrade pip
    - run:
        name: Boostrap Kubash
        command: |
          export PATH=$(pwd)/bin:${HOME}/.kubash/bin/:${HOME}/.local/bin/:${PATH}
          bash bootstrap
    - run:
        name: Test Kubash yaml2cluster
        command: |
          export PATH=$(pwd)/bin:${HOME}/.kubash/bin/:${HOME}/.local/bin/:${PATH}
          export TERM=dumb
          export RAND_TMP=$(uuidgen -r | sha256sum | base64 | head -c 8)
          kubash yaml2cluster examples/example-cluster.yaml -n $RAND_TMP
    - run:
        name: Test Kubectl get nodes
        command: |
          kubectl get nodes
    - run:
        name: Test Kubash tiller
        command: |
          export PATH=$(pwd)/bin:${HOME}/.kubash/bin/:${HOME}/.local/bin/:${PATH}
          export RAND_TMP=$(uuidgen -r | sha256sum | base64 | head -c 8)
          kubash yaml2cluster examples/example-cluster.yaml -n $RAND_TMP
          cp $HOME/.kube/config $HOME/.kubash/clusters/$RAND_TMP/
          echo $KUBERNETES_VERSION > $HOME/.kubash/clusters/$RAND_TMP/kubernetes_version
          echo $HOME/.kubash/clusters/$RAND_TMP/kubernetes_version
          cat $HOME/.kubash/clusters/$RAND_TMP/kubernetes_version
          kubash -n $RAND_TMP tiller
    - run:
        name: Install Bash Automated Testing Suite
        command: |
          export PATH=$(pwd)/bin:${HOME}/.kubash/bin/:${HOME}/.local/bin/:${PATH}
          export TERM=dumb
          make bats
    - run:
        name: Run Bash Automated Testing Suite
        command: |
          export PATH=$(pwd)/bin:${HOME}/.kubash/bin/:${HOME}/.local/bin/:${PATH}
          export TERM=dumb
          bats .ci/.tests.bats
workflows:
  version: 2
  ci:
    jobs:
    - check
    - acceptance-test:
        requires:
        - check
