#!/bin/bash
export PATH=$HOME/.kubash/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export GOPATH=/home/gitlab-runner/.go
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
