#!/bin/bash
build_all () {
 kubash build -y --target-os ubuntu1.13.8 --verbosity=100 
 kubash build -y --target-os ubuntu1.14.4 --verbosity=100 
 kubash build -y --target-os ubuntu1.15.0 --verbosity=100 
 kubash build --builder coreos --target-os coreos 
}
time build_all $@
