#!/bin/bash
if [ $# -ne 1 ]; then
  # Print usage
  echo 'Error! wrong number of arguments'
  echo 'usage:'
  echo "$0 kube_version"
  exit 1
fi
THIS_OS=centos7
KUBE_VERSION=$1
cp -av templates/${THIS_OS}-kube.tpl pax/${THIS_OS}${KUBE_VERSION}
cd pax/${THIS_OS}${KUBE_VERSION}
mv ${THIS_OS}REPLACEME_KUBE_VERSION.json ${THIS_OS}${KUBE_VERSION}.json
sed -i "s/REPLACEME_KUBE_VERSION/${KUBE_VERSION}/g" ${THIS_OS}${KUBE_VERSION}.json
