#!/bin/bash
: ${VERBOSITY:=0}

chkdir () {
  if [ ! -w $1 ] ; then
    sudo mkdir -p $1
    sudo chown $USER. $1
  fi
  if [ ! -w $1 ] ; then
    errror
    echo "Cannot write to $1, please check your permissions"
    exit 2
  fi
}

# these vars are used by the following functions
LINE_TO_ADD=''
TARGET_FILE_FOR_ADD=''

check_if_line_exists()
{
  if [[ $VERBOSITY -gt '7' ]]; then
    echo "Checking for '$LINE_TO_ADD'  in $TARGET_FILE_FOR_ADD"
  fi
  grep -qsFx "$LINE_TO_ADD" $TARGET_FILE_FOR_ADD
}

add_line_to()
{
  if [[ $VERBOSITY -gt '5' ]]; then
    echo "Adding '$LINE_TO_ADD'  to $TARGET_FILE_FOR_ADD"
  fi
  TARGET_FILE=$TARGET_FILE_FOR_ADD
  [ -w "$TARGET_FILE" ] || TARGET_FILE=$TARGET_FILE_FOR_ADD
  printf "%s\n" "$LINE_TO_ADD" | sudo tee -a "$TARGET_FILE"
  sudo systemctl restart apparmor.service
}

main () {
  chkdir /var/lib/libvirt/images
  LINE_TO_ADD='  /var/lib/libvirt/images/*/*/* r,'
  TARGET_FILE_FOR_ADD=/etc/apparmor.d/abstractions/libvirt-qemu  
  check_if_line_exists || add_line_to
}

main $@
