#!/bin/bash
if [ $# -ne 1 ]; then
  # Print usage
  echo 'Error! wrong number of arguments'
  echo 'usage:'
  echo "$0 what_version_kubernetes"
  exit 1
fi
RELEASE_VER=$1
./scripts/stretch $RELEASE_VER
./scripts/centos7 $RELEASE_VER
./scripts/beaver $RELEASE_VER
./scripts/ubuntu $RELEASE_VER
