#!/bin/sh
set -eux
this_pwd=$(pwd)
submodules='istio kubeadm2ha kubespray openshift-ansible rook'

upmodule () {
  cd $this_pwd/submodules/$1
  pwd
  git pull
}
for i in $submodules; do upmodule $i; done
